name: Daily Commit

on:
  schedule:
    - cron: '0 * * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make changes
        run: echo "Daily update" >> log.txt

      - name: Commit and push if changed
        run: |
          git config --global user.email "huangsunchuangyu@outlook.com"
          git config --global user.name "rNLKJA"
          git add -A
          git commit -m "Daily update"
          git push
